apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort
  ports:
    - targetPort: 80 # the port on the container
      port: 80 # the port on the service
      nodePort: 30080 # if not specified, Kubernetes will assign a random port in the range 30000-32767
  selector: # the label selector to match the pods. This should match the labels of the pods you want to expose.
    app: nginx
    tier: frontend
